# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2f65b6bf99afd3b0a85c60c901067ec3ceddeaa4b12457bc96a3c84a66548432487ef3a4395d682c0be5be50e5f9770170041e47305a3cfb875541175dffca

test:
  secret_key_base: 91be15b03cd15d71d6fe70e80698fca0af2e55e3e8c4ad4bb221e441f15077317f4cae46a0a243e2be8ea5df35cbc2babd225c85d6fb31b6c69a892b034d63c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
